[package]
name = "AaveLargePackages"
version = "1.0.0"
upgrade_policy = "compatible"
authors = []

[addresses]
aave_large_packages = "_"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }

[dev-dependencies]