[package]
name = "AaveMockOracle"
version = "1.0.0"
upgrade_policy = "compatible"
authors = []

[addresses]
aave_mock_oracle = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
AaveConfig = { local = "../aave-config" }
AaveAcl = { local = "../aave-acl" }

